### ISSUE TITLE
reporting problem

### ISSUE THREAD

**Issue by Lucifer187** [Block-Build/MusikBot#52]
Hello, I have a little problem with this plugin, I have it on 1.8.8 and under 1.14.4. tested
this message appears in both versions. What would you like to tell us?

https://pastebin.com/dBnWsyFK

 the bot joint and also plays music

**Comment by Block-Build** [comment]
The error occurs while reading the Emojis in BotConfiguration.

**Comment by Lucifer187** [comment]
ok, thanks to your help, the error is no longer displayed, but these warnings, what do they mean and are they relevant as a user or can this message be fixed in the next update? I would like to have my console as free of errors and warnings as possible:

https://pastebin.com/MzGHakpQ

I think the basic idea is great, that comes a little closer to the idea of my server, but now to the main question:

[spigot]
could you program the bot so that the bot plays in the autojoin playlist and this then shows in discord which song is currently being played?

[discord]
Similar to the spigot case, I add a playlist to the bot, it will also be played (with a display showing which song I have added), if a song in the playlist is over, it is unfortunately no longer displayed which song is currently playing (exception skip a song)

**Comment by Block-Build** [comment]
The warning are only nessasary if the bot dosn't work for any case. Just ignore them.

> could you program the bot so that the bot plays in the autojoin playlist and this then shows in discord which song is currently being played?

Maybe i could write it in the channel topic 🤔. What do you think?
![grafik](https://user-images.githubusercontent.com/13054823/100637312-037ffc00-3333-11eb-84f6-cbd5633c6bbd.png)

For aoutoplay on startup you can use the guild configuration:
```
# Should the bot automaticly join the guild after startup?
Auto_Connect_On_Startup:
# Enable or disable
  Enabled: false
# The ID of the VoiceChannel the bot sould join.
# Example: 259798211111726208
  VoiceChannelId: 0
# Should the bot start a track after join?
# Insert an URL.
  Track: ''
```

> Similar to the spigot case, I add a playlist to the bot, it will also be played (with a display showing which song I have added), if a song in the playlist is over, it is unfortunately no longer displayed which song is currently playing (exception skip a song)

You can use this commands for more information about the currently playing track

{prefix} play
{prefix} p
{prefix} info
or
{prefix} queue
{prefix} q

to list all tracks in the queue.
